# Generated by Django 6.1 on 2026-08-16 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_restaurant_rejection_reason_restaurant_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='tag1',
            field=models.CharField(blank=True, default='DineAR', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='tag2',
            field=models.CharField(blank=True, default='Food', max_length=50, null=True),
        ),
    ]
