# Generated by Django 6.1 on 2026-08-16 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0005_remove_menuitem_image_url_remove_menuitem_model_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending Approval'), ('REJECTED', 'Changes Required'), ('APPROVED', 'Approved'), ('SUSPENDED', 'Suspended')], default='PENDING', max_length=20),
        ),
    ]
