# Generated by Django 6.1 on 2026-08-23 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0006_menuitem_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='cuisine',
            field=models.CharField(default='International', max_length=100),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='delivery_time',
            field=models.CharField(default='20-30 MIN', max_length=50),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='price_range',
            field=models.CharField(default='$$', max_length=10),
        ),
    ]
