# Generated by Django 6.1 on 2026-08-25 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0007_restaurant_cuisine_restaurant_delivery_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='category',
            field=models.CharField(default='Fast Food', max_length=100),
        ),
    ]
