# Generated by Django 6.1 on 2026-08-27 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='location',
            unique_together={('name', 'city')},
        ),
    ]
